/**
 * Noms officiels des sociétés BRVM, croisés avec brvmscreener.com et des
 * sources publiques citant le Bulletin Officiel de la Cote (BOC).
 * "Meilleur effort" : pas une vérification exhaustive ligne par ligne contre
 * le site brvm.org officiel. Si une erreur est repérée, corriger ici.
 */
export const BRVM_COMPANY_NAMES: Record<string, { name: string; country: string }> = {
  ABJC: { name: "Servair Abidjan Côte d'Ivoire", country: "Côte d'Ivoire" },
  BICB: { name: "Banque Internationale pour l'Industrie et le Commerce du Bénin", country: "Bénin" },
  BICC: { name: "BICI Côte d'Ivoire", country: "Côte d'Ivoire" },
  BNBC: { name: "Bernabé Côte d'Ivoire", country: "Côte d'Ivoire" },
  BOAB: { name: "Bank of Africa Bénin", country: "Bénin" },
  BOABF: { name: "Bank of Africa Burkina Faso", country: "Burkina Faso" },
  BOAC: { name: "Bank of Africa Côte d'Ivoire", country: "Côte d'Ivoire" },
  BOAM: { name: "Bank of Africa Mali", country: "Mali" },
  BOAN: { name: "Bank of Africa Niger", country: "Niger" },
  BOAS: { name: "Bank of Africa Sénégal", country: "Sénégal" },
  CABC: { name: "Sicable Côte d'Ivoire", country: "Côte d'Ivoire" },
  CBIBF: { name: "Coris Bank International Burkina Faso", country: "Burkina Faso" },
  CFAC: { name: "CFAO Motors Côte d'Ivoire", country: "Côte d'Ivoire" },
  CIEC: { name: "CIE Côte d'Ivoire", country: "Côte d'Ivoire" },
  ECOC: { name: "Ecobank Côte d'Ivoire", country: "Côte d'Ivoire" },
  ETIT: { name: "Ecobank Transnational Incorporated Togo", country: "Togo" },
  FTSC: { name: "Filtisac Côte d'Ivoire", country: "Côte d'Ivoire" },
  LNBB: { name: "Loterie Nationale du Bénin", country: "Bénin" },
  NEIC: { name: "NEI-CEDA Côte d'Ivoire", country: "Côte d'Ivoire" },
  NSBC: { name: "NSIA Banque Côte d'Ivoire", country: "Côte d'Ivoire" },
  NTLC: { name: "Nestlé Côte d'Ivoire", country: "Côte d'Ivoire" },
  ONTBF: { name: "Onatel Burkina Faso", country: "Burkina Faso" },
  ORAC: { name: "Orange Côte d'Ivoire", country: "Côte d'Ivoire" },
  ORGT: { name: "Oragroup Togo", country: "Togo" },
  PALC: { name: "Palm Côte d'Ivoire", country: "Côte d'Ivoire" },
  PRSC: { name: "TractAfric Motors Côte d'Ivoire", country: "Côte d'Ivoire" },
  SAFC: { name: "Safca Côte d'Ivoire", country: "Côte d'Ivoire" },
  SCRC: { name: "Sucrivoire Côte d'Ivoire", country: "Côte d'Ivoire" },
  SDCC: { name: "Sode Côte d'Ivoire", country: "Côte d'Ivoire" },
  SDSC: { name: "Africa Global Logistics Côte d'Ivoire (ex Bolloré CI)", country: "Côte d'Ivoire" },
  SEMC: { name: "Eviosys Packaging Siem Côte d'Ivoire (ex Crown Siem)", country: "Côte d'Ivoire" },
  SGBC: { name: "SGB Côte d'Ivoire", country: "Côte d'Ivoire" },
  SHEC: { name: "Vivo Energy Côte d'Ivoire", country: "Côte d'Ivoire" },
  SIBC: { name: "Société Ivoirienne de Banque Côte d'Ivoire", country: "Côte d'Ivoire" },
  SICC: { name: "Sicor Côte d'Ivoire", country: "Côte d'Ivoire" },
  SIVC: { name: "Erium Côte d'Ivoire (ex Air Liquide CI)", country: "Côte d'Ivoire" },
  SLBC: { name: "Solibra Côte d'Ivoire", country: "Côte d'Ivoire" },
  SMBC: { name: "SMB Côte d'Ivoire", country: "Côte d'Ivoire" },
  SNTS: { name: "Sonatel Sénégal", country: "Sénégal" },
  SOGC: { name: "SOGB Côte d'Ivoire", country: "Côte d'Ivoire" },
  SPHC: { name: "Saph Côte d'Ivoire", country: "Côte d'Ivoire" },
  STAC: { name: "Setao Côte d'Ivoire", country: "Côte d'Ivoire" },
  STBC: { name: "Sitab Côte d'Ivoire", country: "Côte d'Ivoire" },
  SVOC: { name: "Sivoa Côte d'Ivoire", country: "Côte d'Ivoire" },
  TTLC: { name: "TotalEnergies Marketing Côte d'Ivoire", country: "Côte d'Ivoire" },
  TTLS: { name: "TotalEnergies Marketing Sénégal", country: "Sénégal" },
  UNLC: { name: "Unilever Côte d'Ivoire", country: "Côte d'Ivoire" },
  UNXC: { name: "Uniwax Côte d'Ivoire", country: "Côte d'Ivoire" },
};
